<div class="footer">
    <div class="global-center footer-wrap clearfix">
        <ul class="link-wrap-list inline-block">
            <li class="link-wrap-item inline-block">
                <a href="#" class="inline-block">
                    <img src="/static/img/common/logo.png" alt="同学说" class="footer-logo"/>
                </a>
            </li>
            <li class="link-wrap-item inline-block">
                <div class="inline-block">
                    <span class="third-party inline-block weibo-icon"></span>
                </div>
            </li>
            <li class="link-wrap-item inline-block">
                <div class="inline-block wexin">
                    <span  class="third-party weixin-icon inline-block"></span>
                    <div class="ercode"></div>
                </div>
            </li>
        </ul>
        <div class="footer-aside">
            <ul class="about-us-list">
                <li class="inline-block">
                    <a href="/about">关于校园说</a>
                </li>
                <li class="inline-block">
                    <a href="#">帮助中心</a>
                </li>
                <li class="inline-block">
                    <a href="#">联系我们</a>
                </li>
            </ul>
            <p>
                <a href="mailto:contact@campussay.com" style="float:right; display:block;">contact@campussay.com</a>
            </p>
            <p>
                <a href="http://www.miibeian.gov.cn" style="float:right"  target="_blank">渝ICP备16001027号</a>
            </p>
        </div>
    </div>
</div>
	 <!-- 页面的启动脚本文件 start-->
		<#if page.properties['page.javascript']?exists>
		    <script type="text/javascript" data-main="${staticPath}/js/page${page.properties['page.javascript']}" src="${staticPath}/js/lib/r.js"></script>
		</#if>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74134492-1', 'auto');
  ga('send', 'pageview');
</script>
</body>
</html>